services:
  db:
    image: apache/age
    container_name: parallax-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parallax

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
