-- REMOVE FOREIGN KEY
ALTER TABLE person
DROP CONSTRAINT IF EXISTS fk_person_entity;

-- REMOVE entity_id COLUMN
ALTER TABLE person
DROP COLUMN IF EXISTS entity_id;

-- DROP ENTITY TABLE
DROP TABLE IF EXISTS entity;